print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
