
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
print("hello Arbaj khan ")
